swaggeApi: false
debug: false
autoMigrate: true
databases:
  - host: 39.98.66.22
    dialect: mongodb
    port: 27017
    username: root
    password: 123456
    dbName: ke_sjz
    alias: sjz
  - host: 39.98.66.22
    dialect: mysql
    port: 3306
    username: liuxinlei
    password: songzhu12
    dbName: ke_sjz
    alias: sjz